### PR TITLE
xen: fix the example kernel build

### PR DESCRIPTION
**Pull request by djs55**
The current released `mirage` command-line doesn't handle the `-f <config_client.ml>` file properly, see for example https://github.com/mirage/functoria/pull/195 . This PR works around this by separating the client and server unikernels into separate directories.

For anyone unlucky enough to try this on Ubuntu 20.04 LTS, they'll find the Xen packages are broken so I've added some notes on manually working around that.

For anyone lucky/unlucky enough to be on a recent version of Xen (4.10+) they'll discover the `.xl` file nolonger supports the `builder` argument, used by our auto-generated `.xl` files. I've added an `opam pin` note to work around that.

I've added a `README.md` to make it easier for others to run these things.

### CODE REVIEW

**Comment by avsm** [comment]
fixing one of the ocaml-ci errors at https://github.com/ocaml/opam-repository/pull/16652

**Comment by djs55** [comment]
`vchan-unix` now builds on `opensuse` with the `xen-evtchn-unix` and `xen-gnt-unix` pins (see linked PRs)

**Comment by mato** [comment]
@djs55 Thanks for this. I've tried it initially with the existing Xen stack, and have managed to run the test unikernels. On Debian stable (Xen 4.11), `xenconsoled` is started for me so I don't have to do anything special there. Also, Mirage 3.8 fixed the `type=pvh` in the generated `.xl`, so all fine there.

However: What do I need to do to run the test a 2nd time from scratch?

It seems that some information is written to xenstore under `/conduit` when the client connects, and if I destroy and re-create the client, then the server does not notice this.

If I destroy and re-create _both_ the server and client, then the server still sees the old information from the previous run in xenstore, and won't accept the new client either. I tried doing a `sudo xenstore-rm /conduit`, but now I get this when starting the server:

```
Fatal error: exception Xs_protocol.Error("EACCES")
Raised at file "core/xs_protocol.ml", line 685, characters 13-28
Called from file "client_lwt/xs_client_lwt.ml", line 318, characters 13-50
Called from file "src/core/lwt.ml", line 1867, characters 23-26
Re-raised at file "src/core/lwt.ml", line 3027, characters 20-29
Called from file "lib/main.ml", line 35, characters 10-20
Called from file "main.ml" (inlined), line 5, characters 12-25
Called from file "main.ml", line 64, characters 5-10
```

Any ideas?

**Comment by djs55** [comment]
I think you need to re-create the empty `/conduit` tree and set the permissions using https://github.com/mirage/ocaml-vchan/blob/master/lib_test/mirage/init-xenstore.sh i.e.

```
xenstore-rm /conduit
xenstore-write /conduit ""
xenstore-chmod /conduit b0
```

**Comment by mato** [comment]
@avsm Any objections to my merging @djs55's changes as-is? I need to do some updates to ocaml-vchan for the new Xen stack and would prefer to do that with this merged. Otherwise, I can fold Dave's changes into my branch if you'd prefer that.

**Comment by avsm** [comment]
merging is just fine by me! i opened a minor PR in opam-repo to fix opensuse, but that can be tested against trunk

**Pull request merged**
